export const questions = [
  '¿Cuál es tu nombre?',
  '¿Cuál es tu edad?',
  '¿Cuál es tu genero?',
  '¿Cuál es tu programa educativo?',
  '¿Tienes claras las razones por las que estudias?',
  '¿Sueles cambiar con cierta frecuencia el lugar donde estudias en tu casa?',
  '¿Procuras estudiar en aquellas horas en que te encuentras en mejores condiciones para aprender?',
  '¿Te has parado a pensar sobre el número de actividades que realizas cada día y el tiempo que le dedicas a cada una de ellas?',
  '¿Acostumbras a mirar el índice y los apartados más importantes de un tema antes de comenzar a estudiar?',
  '¿Tomas nota de las explicaciones de los profesores?',
  '¿Lees con detenimiento los enunciados de las preguntas',
  '¿Consideras el estudio una ocasión para aprender? ',
  '¿Tu lugar de estudio está alejado de ruidos y otras cosas que impidan concentrarte?',
  'Antes de empezar tu trabajo, ¿haces un esquema de los aspectos más importantes que vas a desarrollar?',
  '¿Sueles dormir, por lo menos, 8 horas cada día?',
  '¿Tienes una idea general de lo que vas a estudiar a lo largo del curso en cada materia o asignatura?',
  'Antes de estudiar el tema con profundidad, ¿realizas una lectura rápida del mismo para hacerte una idea general?',
  'Antes de escribir la respuesta, ¿piensas detenidamente lo que vas a contestar y cómo lo vas a hacer?',
  'Cuando comienzas a estudiar, ¿tardas bastante tiempo en concentrarte? ',
  'En el lugar donde estudias habitualmente, ¿hay personas o cosas que distraen tu atención?',
  'Cuando tomas notas, ¿sueles copiar al pie de la letra lo que dice el profesor?',
  '¿Sueles dormir mal y por la mañana te sientes cansado y poco repuesto?',
  '¿Has elaborado un plan de trabajo en función del tiempo de que dispones y de las asignaturas que tienes?',
  'Cuando has de hacer un trabajo, ¿sueles comentar con tu profesor el esquema y desarrollo del mismo?',
  'Después de una primera lectura del tema, ¿haces una lectura lenta y reposada para buscar las ideas más importantes?',
  'Cuando faltas a clase, ¿sueles informarte a través de un compañero o del profesor de lo que se ha realizado y se ha de realizar?',
  'En un examen o ejercicio, ¿repartes el tiempo para cada pregunta?',
  'Cuando no comprendes algo, ¿lo anotas para luego consultarlo?',
  '¿Tienes luz suficiente (luz natural o lámpara para estudiar sin forzar la vista?',
  '¿Combinas el tiempo que dedicas al estudio con el tiempo de descanso?',
  '¿Dedicas a cada asignatura el tiempo necesario que pueda asegurarte un buen resultado?',
  '¿Subrayas las ideas más importantes a medida que vas estudiando un tema?',
  '¿Sueles abrir un poco la puerta/ventana de tu habitación de estudio para que se ventile?',
  'En el caso que necesites información para hacer un trabajo, ¿sabes cómo encontrarla?',
  '¿Cuidas de que tu expresión escrita sea clara, ordenada y comprensiva?',
  '¿Tratas de estudiar sólo lo justo para una prueba o control?',
  '¿Has notado que los resultados en tus estudios son bajos cuando tienes el tiempo demasiado ocupado en otras cosas?',
  '¿Sigues el plan de trabajo que te has propuesto desde el principio del curso?',
  'En tu lugar de estudio, ¿dispones de suficiente espacio para tener organizado y a mano todo el material que necesitas?',
  'Antes de empezar a estudiar, ¿piensas lo que vas a hacer y cómo vas a distribuir el tiempo?',
  'Resumes lo más importante de cada uno de los apartados del tema, para elaborar después una síntesis general?',
  '¿Cabe en tu mesa todo lo que necesitas para el estudio?',
  'Cuando buscas información en un libro, enciclopedia, etc., para realizar un trabajo, ¿te limitas a copiar al pie de la letra lo que lees?',
  '¿Sueles interrumpir tus sesiones de estudio en casa?',
  '¿Te has acostumbrado a hacer esquemas, croquis, cuadros, gráficos, etc., cuando estudias un tema?',
  '¿Intentas sobreponerte con interés, con ánimo, ante un bajón en las notas? ',
  '¿A tu silla de estudio le falta respaldo? ',
  '¿Tienes organizado todo el material que se ha trabajado en cada materia?',
  '¿La altura de tu silla de estudio te permite apoyar bien los pies en el suelo?',
  'Cuando terminas tu sesión de estudio personal, ¿sueles acabar las tareas que te habías propuesto?',
  '¿La altura de la mesa está proporcionada a la silla?',
  '¿Tienes la costumbre de preparar los exámenes con poco tiempo de antelación?',
  '¿Relacionas el tema estudiado con lo aprendido anteriormente?',
  '¿Descuidas la redacción y presentación del trabajo?',
  '¿Acostumbras a memorizar las ideas más importantes que has resumido en un tema o lección?',
  '¿Pones de tu parte todo lo que puedes para asegurarte unos buenos resultados en tu tarea escolar?',
  '¿Te acercas excesivamente sobre el libro cuando estudias?',
  '¿Aprovechas algún momento del fin de semana para repasar aquellos temas que te han quedado más flojos?',
  'Si te sobra tiempo, ¿entregas el examen inmediatamente sin repasar de nuevo las respuestas?',
  '¿Sueles indicar el nombre de todos aquellos materiales (libros, enciclopedias, revistas, etc.) que has utilizado en el trabajo? ',
]
